config/routes.rb
Rails.application.routes.draw do
  get 'users/profile'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  get '/u/:id', to: 'users#profile', as: 'user'
  
  resources :posts do
    resources :comments
  end

  get 'about', to: 'pages#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "pages#home"
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true, length: {minimum:5, maximum: 50}
    validates :body, presence: true, length: {minimum:10, maximum: 100}
    belongs_to :user
    has_rich_text :body
    has_many :comments, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /posts or /posts.json
  def index
    @posts = Post.all.order(created_at: :desc)
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post.update(views: @post.views + 1)
    @comments = @post.comments.order(created_at: :desc)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.rich_text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="container">
    <h1>Editing Post</h1>

    <%= render 'form' , post: @post %>

    <%= link_to 'Show' , @post %> |
    <%= link_to 'Back' , posts_path %>
</div>

app/views/posts/index.html.erb
<div class="container">
<h1>Welcome to News Feed!</h1>
   <%= link_to "New post", new_post_path, class:"btn btn-secondary" %><br>
      <% @posts.each do |post| %> <br>
          <strong>Title: </strong><%= post.title %> <br>
          <p>posted by <%= link_to post.user.name, user_path(post.user) %></p>
          <p><%= pluralize(post.views, "view") %></p>
          <strong>Body: </strong><%= post.body %> <br>
          <%= link_to 'View this post', post %>
          <%= link_to 'Edit post', edit_post_path(post) %><br>
      <% end %>
</div>
  

app/views/posts/new.html.erb
<div class="container">
    <h1>New Post</h1>

    <%= render 'form' , post: @post %>

    <%= link_to 'Back' , posts_path %>

</div>

app/views/posts/show.html.erb
<div class="container">
  <p id="notice">
    <%= notice %>
  </p>
  <p>

    <strong>Title:</strong>
    <%= @post.title %>
    <p>posted by <%= link_to @post.user.name, user_path(@post.user) %></p>
  </p>

  <p>
    <strong>Body:</strong>
    <%= @post.body %>
  </p>
  <h6><%= pluralize(@post.views, "view") %></h6>
  <%= link_to 'Edit this post' , edit_post_path(@post) %> |
    <%= link_to 'Back' , posts_path %>
      <%= button_to 'Destroy' , @posts, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

<div class="container">
  <%= render 'comments/form', post: @post %>
  <% @comments.each do |comment| %>
    <%= render 'comments/comment', post: @post, comment: comment %>
  <% end %>
</div>