config/routes.rb
Rails.application.routes.draw do
  get 'users/profile'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  get '/u/:id', to: 'users#profile', as: 'user'
  
  resources :posts do
    resources :comments
  end

  get 'about', to: 'pages#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "pages#home"
end

app/views/layouts/_alerts.html.erb
<% if notice %>
    <p class="notice">
        <%= notice %>
    </p>
    <% elsif alert %>
        <p class="alert">
            <%= alert %>
        </p>
        <% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>">Peysbuk</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <%= link_to "Feed" , posts_path, class:'nav-link'%>
        </li>
        <li class="nav-item"> 
          <%= link_to "About" , about_path, class:'nav-link'%>
        </li>

      </ul>
      <ul class="navbar-nav">
        <%= render 'user/session_manager' %>
          </ul>
        </li>
      </ul>

    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>ProjectAppV3</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
      <link rel="stylesheet" type="text/css" href="https://unpkg.com/trix@2.0.0/dist/trix.css">
      <script type="text/javascript" src="https://unpkg.com/trix@2.0.0/dist/trix.umd.min.js"></script>
      <%= stylesheet_link_tag 'application' , media: 'all' , 'data-turbolinks-track' => 'reload' %>
      <%= javascript_pack_tag 'application' , 'data-turbolinks-track' => 'reload' %>
</head>

<body>
  <header>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/alerts' %>
  </header>

  <main>
    <%= yield %>
  </main>
</body>

</html>